/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.113
 * Generated at: 2025-12-12 00:52:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import java.util.List;
import java.text.SimpleDateFormat;
import member.MemberDto;
import member.MemberDao;

public final class memberlist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(7);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("member.MemberDao");
    _jspx_imports_classes.add("member.MemberDto");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css2?family=Dongle&family=Gamja+Flower&family=Nanum+Myeongjo&family=Nanum+Pen+Script&display=swap\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\"\r\n");
      out.write("	integrity=\"sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB\"\r\n");
      out.write("	crossorigin=\"anonymous\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.7.1.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	function funcDel(num) {\r\n");
      out.write("		var ok=confirm(\"정말 삭제하실건가요?\");\r\n");
      out.write("		if(ok){\r\n");
      out.write("			location.href='memberdelete.jsp?num=' + num;\r\n");
      out.write("\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");

 MemberDao dao=new MemberDao();
 ArrayList<MemberDto> list= dao.getAllDatas();

      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	<div style=\"margin: 50px 100px;\">\r\n");
      out.write("		<button type=\"button\" class=\"btn btn-success\"\r\n");
      out.write("			onclick=\"location.href='addform.jsp'\">\r\n");
      out.write("			<i class=\"bi bi-pencil\"></i> 글쓰기\r\n");
      out.write("		</button>\r\n");
      out.write("		<br>\r\n");
      out.write("		<br>\r\n");
      out.write("		<table class=\"table table-bordered\">\r\n");
      out.write("			<caption align=\"top\">\r\n");
      out.write("				<b>member 전체목록</b>\r\n");
      out.write("			</caption>\r\n");
      out.write("			<tr class=\"table-warning\">\r\n");
      out.write("				<th width=\"80\">번호</th>\r\n");
      out.write("				<th width=\"120\">회원명</th>\r\n");
      out.write("				<th width=\"280\">연락처</th>\r\n");
      out.write("				<th width=\"180\">운전면허</th>\r\n");
      out.write("				<th width=\"180\">직업</th>\r\n");
      out.write("				<th width=\"180\">가입일</th>\r\n");
      out.write("				<th width=\"180\">편집</th>\r\n");
      out.write("			</tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			");

        for(int i=0;i<list.size();i++)
        {
            MemberDto dto=list.get(i);
            SimpleDateFormat sdf=new SimpleDateFormat("yyyy년 MM월 dd일 ");
        
      out.write("\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>");
      out.print(dto.getNum() );
      out.write("</td>\r\n");
      out.write("				<td>");
      out.print(dto.getName() );
      out.write("</td>\r\n");
      out.write("				<td>");
      out.print(dto.getHp() );
      out.write("</td>\r\n");
      out.write("				<td>");
      out.print(dto.getDriver() );
      out.write("</td>\r\n");
      out.write("				<td>");
      out.print(dto.getJop() );
      out.write("</td>\r\n");
      out.write("				<td>");
      out.print(sdf.format(dto.getWriteday()));
      out.write("</td>\r\n");
      out.write("				<td>\r\n");
      out.write("				<!-- \r\n");
      out.write("				 location.href='파일명?파라미터=값'\r\n");
      out.write("				    ✔ URL 이동 시 주의사항\r\n");
      out.write("				    - onclick 안에서 location.href 로 페이지 이동할 때\r\n");
      out.write("				      파일명/경로의 대소문자가 틀리면 404 에러 발생함.\r\n");
      out.write("				      (윈도우는 대소문자 구분을 잘 안 하지만, 서버에서는 구분됨)\r\n");
      out.write("				\r\n");
      out.write("				    ✔ updateform.jsp 와 memberdelete.jsp 로 이동하면서\r\n");
      out.write("				      각 회원의 num 값을 쿼리스트링(?num=)으로 전달한다.\r\n");
      out.write("				-->\r\n");
      out.write("				   <!-- 수정 버튼: updateform.jsp 로 이동, 해당 회원의 num 값 전달 -->\r\n");
      out.write("\r\n");
      out.write("					<button type=\"button\" class=\"btn btn-info btn-sm\"\r\n");
      out.write("						onclick=\"location.href='updateform.jsp?num=");
      out.print(dto.getNum());
      out.write("'\">수정</button>\r\n");
      out.write("					  <!-- 삭제 버튼: memberdelete.jsp 로 이동, 해당 회원의 num 값 전달 -->\r\n");
      out.write("					<button type=\"button\" class=\"btn btn-danger btn-sm\"\r\n");
      out.write("   						onclick=\"funcDel(");
      out.print(dto.getNum());
      out.write(")\">삭제</button>\r\n");
      out.write("\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			");
}
       
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		</table>\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
